# Generated by Django 5.2.11 on 2026-03-13

from django.db import migrations


INITIAL_QUESTIONS = [
    {
        'question_text': "Which festival is strongly associated with Assam's spring harvest traditions?",
        'option_a': 'Onam',
        'option_b': 'Lohri',
        'option_c': 'Bihu',
        'option_d': 'Ganesh Chaturthi',
        'correct_answer': 'c',
        'category': 'festival',
        'tags': ['festival', 'heritage'],
        'difficulty': 'easy',
        'explanation': 'Bihu is one of Assam\'s most recognizable harvest festivals and marks the spring agricultural cycle.',
        'approved': True,
    },
    {
        'question_text': 'The dance-drama form Kathakali is historically rooted in which state?',
        'option_a': 'Punjab',
        'option_b': 'Kerala',
        'option_c': 'Gujarat',
        'option_d': 'Bihar',
        'correct_answer': 'b',
        'category': 'dance',
        'tags': ['dance', 'heritage'],
        'difficulty': 'easy',
        'explanation': 'Kathakali developed in Kerala and remains one of the state\'s most iconic performance traditions.',
        'approved': True,
    },
    {
        'question_text': 'Which option best describes intangible cultural heritage?',
        'option_a': 'Living practices like songs, rituals, and oral traditions',
        'option_b': 'Only protected archaeological monuments',
        'option_c': 'Modern concrete architecture in urban centers',
        'option_d': 'Only objects displayed in museums',
        'correct_answer': 'a',
        'category': 'heritage',
        'tags': ['heritage', 'language', 'ritual'],
        'difficulty': 'medium',
        'explanation': 'Intangible heritage focuses on living traditions such as oral practices, rituals, music, and community knowledge.',
        'approved': True,
    },
    {
        'question_text': 'Pongal is primarily celebrated as a harvest festival in:',
        'option_a': 'West Bengal',
        'option_b': 'Maharashtra',
        'option_c': 'Odisha',
        'option_d': 'Tamil Nadu',
        'correct_answer': 'd',
        'category': 'festival',
        'tags': ['festival', 'food', 'ritual'],
        'difficulty': 'easy',
        'explanation': 'Pongal is a major harvest festival of Tamil Nadu and includes both thanksgiving rituals and traditional food preparation.',
        'approved': True,
    },
    {
        'question_text': "Which city is famous for the classical dance form Bharatanatyam's institutional revival?",
        'option_a': 'Chennai',
        'option_b': 'Jaipur',
        'option_c': 'Lucknow',
        'option_d': 'Shimla',
        'correct_answer': 'a',
        'category': 'dance',
        'tags': ['dance', 'heritage'],
        'difficulty': 'medium',
        'explanation': 'Chennai became a major center for Bharatanatyam revival through sabhas, schools, and cultural institutions.',
        'approved': True,
    },
    {
        'question_text': 'What is the strongest reason to document regional food traditions?',
        'option_a': 'To rank dishes by popularity',
        'option_b': 'To remove local recipe variation',
        'option_c': 'To preserve community memory and identity',
        'option_d': 'To replace home cooking with standard menus',
        'correct_answer': 'c',
        'category': 'food',
        'tags': ['food', 'heritage'],
        'difficulty': 'easy',
        'explanation': 'Food traditions carry memory, migration, ritual, and identity, which is why documenting them matters culturally.',
        'approved': True,
    },
    {
        'question_text': 'Which language is primarily spoken in Tamil Nadu?',
        'option_a': 'Tamil',
        'option_b': 'Punjabi',
        'option_c': 'Konkani',
        'option_d': 'Bodo',
        'correct_answer': 'a',
        'category': 'language',
        'tags': ['language'],
        'difficulty': 'easy',
        'explanation': 'Tamil Nadu is the principal region for the Tamil language, one of the oldest living classical languages.',
        'approved': True,
    },
    {
        'question_text': 'Which script is most commonly used to write Punjabi in India?',
        'option_a': 'Devanagari',
        'option_b': 'Gurmukhi',
        'option_c': 'Tamil',
        'option_d': 'Roman',
        'correct_answer': 'b',
        'category': 'language',
        'tags': ['language', 'heritage'],
        'difficulty': 'medium',
        'explanation': 'Punjabi is commonly written in Gurmukhi in India, especially in Punjab.',
        'approved': True,
    },
    {
        'question_text': 'Which monument is a UNESCO World Heritage site in Agra?',
        'option_a': 'Charminar',
        'option_b': 'Sanchi Stupa',
        'option_c': 'Taj Mahal',
        'option_d': 'Konark Sun Temple',
        'correct_answer': 'c',
        'category': 'heritage',
        'tags': ['heritage'],
        'difficulty': 'easy',
        'explanation': 'The Taj Mahal in Agra is one of India\'s best-known UNESCO World Heritage sites.',
        'approved': True,
    },
    {
        'question_text': 'Which meal tradition is closely associated with community kitchens in Punjab?',
        'option_a': 'Sadya',
        'option_b': 'Langar',
        'option_c': 'Undhiyu',
        'option_d': 'Poha',
        'correct_answer': 'b',
        'category': 'food',
        'tags': ['food', 'ritual'],
        'difficulty': 'medium',
        'explanation': 'Langar is the shared community meal tradition most closely associated with Sikh institutions in Punjab.',
        'approved': True,
    },
    {
        'question_text': 'What is the main purpose of ritual lamp lighting during many cultural ceremonies?',
        'option_a': 'To mark the beginning with an auspicious symbol',
        'option_b': 'To replace all spoken prayers',
        'option_c': 'To end the ceremony early',
        'option_d': 'To identify the chief guest only',
        'correct_answer': 'a',
        'category': 'ritual',
        'tags': ['ritual', 'heritage'],
        'difficulty': 'easy',
        'explanation': 'Lamp lighting often symbolizes knowledge, auspiciousness, and the formal opening of a ceremony.',
        'approved': True,
    },
    {
        'question_text': 'Why do harvest festivals remain important in many regions of India?',
        'option_a': 'They remove all local differences',
        'option_b': 'They connect seasonal labor, gratitude, and community memory',
        'option_c': 'They are only tourist events',
        'option_d': 'They replace regional languages with one national format',
        'correct_answer': 'b',
        'category': 'ritual',
        'tags': ['festival', 'ritual', 'heritage'],
        'difficulty': 'medium',
        'explanation': 'Harvest festivals carry agricultural rhythms, shared gratitude, and cultural memory across generations.',
        'approved': True,
    },
]


def seed_questions(apps, schema_editor):
    QuizQuestion = apps.get_model('core', 'QuizQuestion')

    for question in INITIAL_QUESTIONS:
        QuizQuestion.objects.update_or_create(
            question_text=question['question_text'],
            defaults=question,
        )


def remove_seed_questions(apps, schema_editor):
    QuizQuestion = apps.get_model('core', 'QuizQuestion')
    QuizQuestion.objects.filter(question_text__in=[question['question_text'] for question in INITIAL_QUESTIONS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quiz_system'),
    ]

    operations = [
        migrations.RunPython(seed_questions, remove_seed_questions),
    ]