# Generated by Django 5.2.11 on 2026-03-13

import json
from pathlib import Path
from django.db import migrations


QUIZ_CATEGORY_ORDER = (
    "festival",
    "food",
    "tradition",
    "clothing",
    "ritual",
    "language",
    "dance",
    "music",
    "folklore",
    "architecture",
    "heritage",
)

QUIZ_CATEGORY_BLOCK_SIZE = 100


def _normalize_token(value):
    return str(value or "").strip().lower().replace("-", "_").replace(" ", "_")


def _resolve_question_category(index, raw_category):
    normalized_category = _normalize_token(raw_category)
    if normalized_category in QUIZ_CATEGORY_ORDER:
        return normalized_category

    block_index = min(index // QUIZ_CATEGORY_BLOCK_SIZE, len(QUIZ_CATEGORY_ORDER) - 1)
    return QUIZ_CATEGORY_ORDER[block_index]


def _resolve_question_tags(category, raw_tags):
    if isinstance(raw_tags, str):
        raw_values = [token.strip() for token in raw_tags.split(",")]
    elif isinstance(raw_tags, (list, tuple, set)):
        raw_values = list(raw_tags)
    else:
        raw_values = []

    normalized_tags = []
    for raw_tag in raw_values:
        normalized_tag = _normalize_token(raw_tag)
        if normalized_tag and normalized_tag not in normalized_tags:
            normalized_tags.append(normalized_tag)

    if category not in normalized_tags:
        normalized_tags.insert(0, category)

    return normalized_tags


def _load_quiz_questions():
    """Load quiz questions from JSON data file."""
    data_dir = Path(__file__).resolve().parent.parent.parent.parent / 'data'
    filepath = data_dir / 'quiz_questions.json'
    
    if filepath.exists():
        try:
            with open(filepath, 'r', encoding='utf-8-sig') as f:
                raw_questions = json.load(f)

            prepared_questions = []
            for index, raw_question in enumerate(raw_questions):
                if not isinstance(raw_question, dict):
                    continue

                prepared_question = dict(raw_question)
                resolved_category = _resolve_question_category(index, prepared_question.get('category'))
                prepared_question['category'] = resolved_category
                prepared_question['tags'] = _resolve_question_tags(resolved_category, prepared_question.get('tags'))
                prepared_questions.append(prepared_question)

            return prepared_questions
        except (json.JSONDecodeError, IOError):
            pass
    
    return []


def seed_questions(apps, schema_editor):
    QuizQuestion = apps.get_model('core', 'QuizQuestion')
    questions = _load_quiz_questions()
    
    for question in questions:
        QuizQuestion.objects.update_or_create(
            question_text=question['question_text'],
            defaults=question,
        )


def remove_seed_questions(apps, schema_editor):
    QuizQuestion = apps.get_model('core', 'QuizQuestion')
    questions = _load_quiz_questions()
    QuizQuestion.objects.filter(
        question_text__in=[q['question_text'] for q in questions]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quiz_system'),
    ]

    operations = [
        migrations.RunPython(seed_questions, remove_seed_questions),
    ]