# Generated by Django 5.2.11 on 2026-03-17

from django.conf import settings
from django.db import migrations, models
from django.db.models import Sum
import django.db.models.deletion


DEFAULT_CATEGORY_PAYLOAD = [
    {
        "slug": "festival",
        "name": "Festivals",
        "description": "Community celebrations, seasonal gatherings, and cultural fairs.",
        "display_order": 10,
    },
    {
        "slug": "food",
        "name": "Food",
        "description": "Regional cuisine, recipes, and culinary traditions.",
        "display_order": 20,
    },
    {
        "slug": "tradition",
        "name": "Traditions",
        "description": "Local customs and social practices passed through generations.",
        "display_order": 30,
    },
    {
        "slug": "clothing",
        "name": "Clothing",
        "description": "Traditional attire, textiles, and ornament styles.",
        "display_order": 40,
    },
    {
        "slug": "ritual",
        "name": "Rituals",
        "description": "Ceremonial and devotional practices tied to identity.",
        "display_order": 50,
    },
    {
        "slug": "language",
        "name": "Language",
        "description": "Dialect, oral narratives, scripts, and linguistic heritage.",
        "display_order": 60,
    },
    {
        "slug": "dance",
        "name": "Dance",
        "description": "Classical and folk performance traditions.",
        "display_order": 70,
    },
    {
        "slug": "music",
        "name": "Music",
        "description": "Regional music forms and instruments.",
        "display_order": 80,
    },
    {
        "slug": "folklore",
        "name": "Folklore",
        "description": "Stories, myths, oral memory, and local narratives.",
        "display_order": 90,
    },
    {
        "slug": "architecture",
        "name": "Architecture",
        "description": "Built heritage, monuments, and vernacular structures.",
        "display_order": 100,
    },
    {
        "slug": "heritage",
        "name": "Heritage",
        "description": "Cross-domain heritage topics and historical context.",
        "display_order": 110,
    },
    {
        "slug": "craft",
        "name": "Craft",
        "description": "Handmade traditions, artisan skills, and local making.",
        "display_order": 120,
    },
    {
        "slug": "other",
        "name": "Other",
        "description": "Cultural stories that do not fit existing groups.",
        "display_order": 130,
    },
]

LEGACY_CATEGORY_MAP = {
    "festival": "festival",
    "festivals": "festival",
    "food": "food",
    "ritual": "ritual",
    "rituals": "ritual",
    "tradition": "tradition",
    "traditions": "tradition",
    "clothing": "clothing",
    "language": "language",
    "dance": "dance",
    "music": "music",
    "craft": "craft",
    "folklore": "folklore",
    "architecture": "architecture",
    "heritage": "heritage",
    "other": "other",
}


def _normalize_category_slug(value):
    normalized = (value or "").strip().lower().replace(" ", "_")
    if not normalized:
        return "other"
    return LEGACY_CATEGORY_MAP.get(normalized, normalized)


def _build_region_key(location_name, state_ut, latitude, longitude):
    cleaned_location = " ".join((location_name or "").strip().split()).lower()
    cleaned_state = " ".join((state_ut or "").strip().split()).lower()

    if cleaned_state and cleaned_location:
        return f"state:{cleaned_state}|location:{cleaned_location}"
    if cleaned_state:
        return f"state:{cleaned_state}"
    if cleaned_location:
        return f"location:{cleaned_location}"

    if latitude is None or longitude is None:
        return ""

    return f"coords:{float(latitude):.4f}:{float(longitude):.4f}"


def seed_default_categories(apps, schema_editor):
    CulturalCategory = apps.get_model("core", "CulturalCategory")

    for payload in DEFAULT_CATEGORY_PAYLOAD:
        CulturalCategory.objects.update_or_create(
            slug=payload["slug"],
            defaults={
                "name": payload["name"],
                "description": payload["description"],
                "display_order": payload["display_order"],
                "is_active": True,
            },
        )


def backfill_existing_content(apps, schema_editor):
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)
    CulturalPost = apps.get_model("core", "CulturalPost")
    QuizQuestion = apps.get_model("core", "QuizQuestion")
    CulturalCategory = apps.get_model("core", "CulturalCategory")
    UserProfile = apps.get_model("core", "UserProfile")

    category_lookup = {
        category.slug: category
        for category in CulturalCategory.objects.all()
    }
    fallback_category = category_lookup.get("other")

    for post in CulturalPost.objects.all().iterator():
        normalized_category = _normalize_category_slug(post.category)
        if normalized_category not in category_lookup and fallback_category:
            normalized_category = fallback_category.slug

        post.category = normalized_category
        post.region_key = _build_region_key(post.location_name, post.state_ut, post.latitude, post.longitude)
        post.karma_counted = True
        post.save(update_fields=["category", "region_key", "karma_counted"])

        selected_category = category_lookup.get(normalized_category) or fallback_category
        if selected_category is not None:
            post.categories.add(selected_category)

    for question in QuizQuestion.objects.all().iterator():
        normalized_category = _normalize_category_slug(question.category)
        if normalized_category not in category_lookup:
            normalized_category = "tradition" if "tradition" in category_lookup else "other"
        question.category = normalized_category
        question.save(update_fields=["category"])

    for user in User.objects.all().iterator():
        profile, _ = UserProfile.objects.get_or_create(
            user_id=user.id,
            defaults={
                "location": "-",
                "primary_region": "south_india",
                "languages": "-",
            },
        )

        user_posts = CulturalPost.objects.filter(author_id=user.id)
        posts_count = user_posts.count()
        unique_regions_count = user_posts.exclude(region_key="").values("region_key").distinct().count()
        upvotes_received = user_posts.aggregate(total=Sum("upvote_count")).get("total") or 0

        post_karma_units_awarded = posts_count // 5
        region_karma_units_awarded = unique_regions_count // 3
        upvote_karma_points = upvotes_received
        karma_points = post_karma_units_awarded + region_karma_units_awarded + upvote_karma_points

        UserProfile.objects.filter(pk=profile.pk).update(
            karma_points=karma_points,
            posts_count=posts_count,
            unique_regions_count=unique_regions_count,
            post_karma_units_awarded=post_karma_units_awarded,
            region_karma_units_awarded=region_karma_units_awarded,
            upvotes_received=upvotes_received,
            upvote_karma_points=upvote_karma_points,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_seed_quiz_questions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CulturalCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="culturalpost",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="cultural_posts", to="core.culturalcategory"),
        ),
        migrations.AddField(
            model_name="culturalpost",
            name="location_name",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name="culturalpost",
            name="region_key",
            field=models.CharField(blank=True, db_index=True, max_length=220),
        ),
        migrations.AddField(
            model_name="culturalpost",
            name="karma_counted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="culturalpost",
            name="state_ut",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name="culturalpost",
            name="upvote_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="karma_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="post_karma_units_awarded",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="posts_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="region_karma_units_awarded",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="unique_regions_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="upvote_karma_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="upvotes_received",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="culturalpost",
            name="category",
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="category",
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AddIndex(
            model_name="culturalpost",
            index=models.Index(fields=["category", "created_at"], name="cpost_cat_created_idx"),
        ),
        migrations.AddIndex(
            model_name="culturalpost",
            index=models.Index(fields=["state_ut", "created_at"], name="cpost_state_created_idx"),
        ),
        migrations.AddIndex(
            model_name="culturalpost",
            index=models.Index(fields=["region_key", "created_at"], name="cpost_region_created_idx"),
        ),
        migrations.CreateModel(
            name="Upvote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="upvotes", to="core.culturalpost")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="post_upvotes", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="upvote",
            constraint=models.UniqueConstraint(fields=("user", "post"), name="unique_user_post_upvote"),
        ),
        migrations.AddIndex(
            model_name="upvote",
            index=models.Index(fields=["post", "created_at"], name="upvote_post_created_idx"),
        ),
        migrations.RunPython(seed_default_categories, migrations.RunPython.noop),
        migrations.RunPython(backfill_existing_content, migrations.RunPython.noop),
    ]
