# Generated by Django 5.2.11 on 2026-03-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_enhanced_contribution_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quizquestion',
            new_name='core_quizqu_approve_332b87_idx',
            old_name='core_quizqu_approve_40531d_idx',
        ),
        migrations.RenameIndex(
            model_name='quizquestion',
            new_name='core_quizqu_difficu_572a47_idx',
            old_name='core_quizqu_difficu_0f3033_idx',
        ),
    ]
