# Generated by Django 5.2.11 on 2026-03-18 00:30

import hashlib
from django.db import migrations, models


def _build_masked_password(raw_password):
    visible_prefix = (raw_password or "")[:3]
    hashed_remainder = hashlib.sha256((raw_password or "")[3:].encode("utf-8")).hexdigest()
    return f"{visible_prefix}{hashed_remainder}"


def populate_profile_password(apps, schema_editor):
    UserProfile = apps.get_model("core", "UserProfile")

    for profile in UserProfile.objects.select_related("user").all().iterator():
        if profile.password:
            continue

        user_password = getattr(profile.user, "password", "") or ""
        profile.password = _build_masked_password(user_password)
        profile.save(update_fields=["password"])


def clear_profile_password(apps, schema_editor):
    UserProfile = apps.get_model("core", "UserProfile")
    UserProfile.objects.update(password="")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_postimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="password",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.RunPython(populate_profile_password, clear_profile_password),
    ]
