# Generated by Django 5.2.11 on 2026-03-18 01:00

from django.db import migrations


KARMA_LOCATION_THRESHOLD = 5


def recalculate_karma_for_location_rule(apps, schema_editor):
    UserProfile = apps.get_model("core", "UserProfile")
    CulturalPost = apps.get_model("core", "CulturalPost")

    for profile in UserProfile.objects.select_related("user").all().iterator():
        user_posts = CulturalPost.objects.filter(author_id=profile.user_id)

        post_count = user_posts.count()
        location_count = user_posts.exclude(region_key="").values("region_key").distinct().count()
        upvotes_received = sum(post.upvote_count for post in user_posts.only("upvote_count"))

        location_units = location_count // KARMA_LOCATION_THRESHOLD

        profile.posts_count = post_count
        profile.unique_regions_count = location_count
        profile.post_karma_units_awarded = 0
        profile.region_karma_units_awarded = location_units
        profile.upvotes_received = upvotes_received
        profile.upvote_karma_points = upvotes_received
        profile.karma_points = location_units + upvotes_received
        profile.save(
            update_fields=[
                "posts_count",
                "unique_regions_count",
                "post_karma_units_awarded",
                "region_karma_units_awarded",
                "upvotes_received",
                "upvote_karma_points",
                "karma_points",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_userprofile_password"),
    ]

    operations = [
        migrations.RunPython(recalculate_karma_for_location_rule, migrations.RunPython.noop),
    ]
