# Generated by Django 5.2.11 on 2026-03-18

import json
from pathlib import Path

from django.db import migrations


QUIZ_CATEGORY_ORDER = (
    "festival",
    "food",
    "tradition",
    "clothing",
    "ritual",
    "language",
    "dance",
    "music",
    "folklore",
    "architecture",
    "heritage",
)

QUIZ_CATEGORY_BLOCK_SIZE = 100


def _normalize_token(value):
    return str(value or "").strip().lower().replace("-", "_").replace(" ", "_")


def _resolve_question_category(index, raw_category):
    normalized_category = _normalize_token(raw_category)
    if normalized_category in QUIZ_CATEGORY_ORDER:
        return normalized_category

    block_index = min(index // QUIZ_CATEGORY_BLOCK_SIZE, len(QUIZ_CATEGORY_ORDER) - 1)
    return QUIZ_CATEGORY_ORDER[block_index]


def _resolve_question_tags(category, raw_tags):
    if isinstance(raw_tags, str):
        raw_values = [token.strip() for token in raw_tags.split(",")]
    elif isinstance(raw_tags, (list, tuple, set)):
        raw_values = list(raw_tags)
    else:
        raw_values = []

    normalized_tags = []
    for raw_tag in raw_values:
        normalized_tag = _normalize_token(raw_tag)
        if normalized_tag and normalized_tag not in normalized_tags:
            normalized_tags.append(normalized_tag)

    if category not in normalized_tags:
        normalized_tags.insert(0, category)

    return normalized_tags


def _build_question_metadata_lookup():
    data_dir = Path(__file__).resolve().parent.parent.parent.parent / "data"
    filepath = data_dir / "quiz_questions.json"

    if not filepath.exists():
        return {}

    try:
        with open(filepath, "r", encoding="utf-8-sig") as file_handle:
            raw_questions = json.load(file_handle)
    except (json.JSONDecodeError, IOError):
        return {}

    metadata_lookup = {}
    for index, raw_question in enumerate(raw_questions):
        if not isinstance(raw_question, dict):
            continue

        question_text = str(raw_question.get("question_text") or "").strip()
        if not question_text:
            continue

        resolved_category = _resolve_question_category(index, raw_question.get("category"))
        resolved_tags = _resolve_question_tags(resolved_category, raw_question.get("tags"))
        metadata_lookup[question_text] = {
            "category": resolved_category,
            "tags": resolved_tags,
        }

    return metadata_lookup


def backfill_quiz_category_and_tags(apps, schema_editor):
    QuizQuestion = apps.get_model("core", "QuizQuestion")
    metadata_lookup = _build_question_metadata_lookup()
    if not metadata_lookup:
        return

    questions_to_update = []

    for quiz_question in QuizQuestion.objects.all().only("id", "question_text", "category", "tags").iterator():
        metadata = metadata_lookup.get(quiz_question.question_text)
        if not metadata:
            continue

        changed = False
        if quiz_question.category != metadata["category"]:
            quiz_question.category = metadata["category"]
            changed = True

        existing_tags = list(quiz_question.tags or [])
        if existing_tags != metadata["tags"]:
            quiz_question.tags = metadata["tags"]
            changed = True

        if changed:
            questions_to_update.append(quiz_question)

    if questions_to_update:
        QuizQuestion.objects.bulk_update(questions_to_update, ["category", "tags"], batch_size=200)


def reverse_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_recalculate_karma_location_only"),
    ]

    operations = [
        migrations.RunPython(backfill_quiz_category_and_tags, reverse_noop),
    ]
