# Generated by Django 5.2.11 on 2026-04-03 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_useractivity_message_is_delivered_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureQuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('quick', 'Quick Play'), ('marathon', 'Marathon Mode'), ('daily', 'Daily Challenge')], default='quick', max_length=20)),
                ('total_questions', models.PositiveIntegerField(default=10)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_quest_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CultureQuestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guessed_state', models.CharField(blank=True, max_length=80)),
                ('correct_state', models.CharField(max_length=80)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_quest_answers', to='core.culturalpost')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.culturequestsession')),
            ],
            options={
                'ordering': ['answered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='culturequestsession',
            index=models.Index(fields=['user', '-started_at'], name='cquest_user_started_idx'),
        ),
        migrations.AddIndex(
            model_name='culturequestsession',
            index=models.Index(fields=['mode', '-score'], name='cquest_mode_score_idx'),
        ),
        migrations.AddIndex(
            model_name='culturequestanswer',
            index=models.Index(fields=['session', 'answered_at'], name='cquest_ans_session_idx'),
        ),
    ]
