from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('developers/', views.developers, name='developers'),
    path('register/', views.register, name="register"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('explore/', views.explore_india, name='explore_india'),
    path('culture/', views.culture, name='culture'),
    path('spotlight/', views.spotlight, name='spotlight'),
    path('discover/', views.discover, name='discover'),
    path('discover/state/<slug:state_slug>/', views.discover_by_state, name='discover_by_state'),
    path('discover/post/<int:post_id>/upvote/', views.upvote_post, name='upvote_post'),
    path('quiz/', views.quiz_page, name='quiz'),
    path('quiz/practice/', views.quiz_practice, name='quiz_practice'),
    path('quiz/timed/', views.quiz_timed, name='quiz_timed'),
    path('quiz/daily/', views.quiz_daily, name='quiz_daily'),
    path('culture-quest/', views.culture_quest, name='culture_quest'),
    path('culture-quest/start/', views.culture_quest_start, name='culture_quest_start'),
    path('culture-quest/question/', views.culture_quest_question, name='culture_quest_question'),
    path('culture-quest/submit/', views.culture_quest_submit, name='culture_quest_submit'),
    path('culture-quest/leaderboard/', views.culture_quest_leaderboard, name='culture_quest_leaderboard'),
    path('chat/', views.chat_home, name='chat_home'),
    path('chat/user-search/', views.chat_user_search, name='chat_user_search'),
    path('chat/activity/update/', views.chat_update_user_activity, name='chat_update_user_activity'),
    path('chat/activity/offline/', views.chat_set_offline, name='chat_set_offline'),
    path('chat/<str:username>/send/', views.chat_send_message, name='chat_send_message'),
    path('chat/<str:username>/messages/', views.chat_fetch_messages, name='chat_fetch_messages'),
    path('chat/<str:username>/delivered/', views.chat_mark_messages_delivered, name='chat_mark_messages_delivered'),
    path('chat/<str:username>/typing/', views.chat_typing_indicator, name='chat_typing_indicator'),
    path('chat/<str:username>/check-typing/', views.chat_check_typing, name='chat_check_typing'),
    path('chat/<str:username>/online-status/', views.chat_check_online_status, name='chat_check_online_status'),
    path('chat/<str:username>/', views.chat_conversation, name='chat_conversation'),
    path('api/geocode/', views.geocode_search, name='geocode_search'),
    path('api/reverse-geocode/', views.reverse_geocode, name='reverse_geocode'),
    path('upload/', views.upload, name='upload'),
    path('my-posts/', views.my_posts, name='my_posts'),
    path('my-posts/state/<slug:state_slug>/', views.my_posts_by_state, name='my_posts_by_state'),
    path('my-posts/<int:post_id>/delete/', views.delete_my_post, name='delete_my_post'),
    path('login/', views.SanskritiLoginView.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
]